lsst-epo/investigation-static

src/assets/icons/fast-forward.svg, src/assets/icons/fast-rewind.svg, src/assets/icons/pause.svg, src/assets/icons/play.svg, src/components/charts/supernovaSelector/Blinker.jsx, src/components/charts/supernovaSelector/BlinkerControls.jsx, src/components/charts/supernovaSelector/BlinkerImage.jsx, src/components/charts/supernovaSelector/index.jsx, src/components/charts/supernovaSelector/styles.module.scss, src/components/charts/supernovaSelector/supernovaSelectorUtilities.js, src/components/site/icons/FastForward.jsx, src/components/site/icons/Pause.jsx, src/components/site/icons/Play.jsx, src/components/site/icons/Rewind.jsx, src/containers/SupernovaSelectorContainer.jsx
Includes broadcasting active alert id (based on image name) up
to parent component (SupernovaSelectorContainer) in anticipation
of sharing this updating id with sibling components  (LightCurve)
=> [EPO-2337] Add playback controls to SupernovaSelector

src/components/charts/lightCurve/Template.jsx, src/components/charts/lightCurve/Templates.jsx, src/components/charts/lightCurve/index.jsx, src/containers/PageContainer.jsx, src/containers/SupernovaSelectorWithLightCurveContainer.jsx, src/data/pages/searching-for-supernovae-1-1.json
rebase onto master and squash commits into one
=> [EPO-2420] Light curve graph has togglable templates  

src/components/charts/lightCurve/index.jsx, src/components/charts/lightCurve/light-curve.module.scss, src/components/charts/supernovaSelector/Points.jsx, src/components/charts/supernovaSelector/index.jsx, src/containers/PageContainer.jsx, src/containers/SupernovaSelectorWithLightCurveContainer.jsx, src/data/pages/blinking-supernovae.json, src/data/pages/discovering-supernovae.json, src/data/pages/distance-to-supernovae-1-2.json, src/data/pages/observing-supernovae.json, src/data/pages/searching-for-supernovae-1.json, src/data/pages/searching-for-supernovae-2.json, src/data/pages/searching-for-supernovae-3-1.json, src/data/pages/searching-for-supernovae-3.json
Blinker and light curve graph should only "update in sync" those alerts corresponding to active supernova frames
=> [EPO-2417] Blinker and light curve graph: "update in sync"

src/components/charts/hubblePlot/HubblePlot2D.jsx, src/components/charts/hubblePlot/Points.jsx, src/components/charts/hubblePlot/XAxis.jsx, src/components/qas/questions/Prompt.jsx, src/containers/HubblePlot2DContainer.jsx, src/containers/PageContainer.jsx, src/containers/SupernovaSelectorWithLightCurveContainer.jsx, src/data/pages/blinking-supernovae.json, src/data/pages/interpreting-hubble-plot-2.json
Placholder logic to handle what galaxy to plot, but otherwise
successfully cycles through available galaxies based on data AND
generates answer AND checks for answer in order to recompose user
generated plot on page load/reload
=> [EPO-2492] User generated Hubble Plot with QAing

src/components/charts/galaxySelector/Point.jsx, src/components/charts/galaxySelector/Points.jsx, src/components/charts/galaxySelector/index.jsx, src/components/charts/galaxySelector/styles.module.scss, src/containers/GalaxySelectorContainer.jsx, src/containers/scatter-plot-selector-container.scss, src/data/pages/interpreting-hubble-plot-1.json, static/data/galaxies/galaxy_selector.json
Send object of 2 selections back to parent and store for legend
=> [EPO-2475] GalaxySelector support for multiple selections

src/components/charts/hubblePlot/HubblePlot3D.jsx
=> [C] Display label for points with label field

src/components/charts/galaxySelector/blinker/BlinkerControls.jsx, src/components/charts/shared/navDrawer/nav-drawer.module.scss, src/components/charts/shared/navDrawer/toolbar/index.jsx, src/components/page/TwoCol.jsx, src/components/page/index.jsx, src/components/page/page.module.scss, src/components/site/forms/table/index.jsx, src/containers/GalaxyScramblerContainer.jsx, src/containers/GalaxySelectorContainer.jsx, src/containers/ScatterPlotSelectorContainer.jsx, src/containers/SupernovaSelectorWithLightCurveContainer.jsx
Encompasses:
- https://jira.lsstcorp.org/browse/EPO-2613
- https://jira.lsstcorp.org/browse/EPO-2610
- https://jira.lsstcorp.org/browse/EPO-2611
- https://jira.lsstcorp.org/browse/EPO-2615
- https://jira.lsstcorp.org/browse/EPO-2618
- https://jira.lsstcorp.org/browse/EPO-2630
=> Bug fixes for multiple tickets

package.json, src/components/charts/largeScaleStructurePlot/index.jsx, src/components/charts/largeScaleStructurePlot/large-scale-structure-plot.module.scss, src/components/charts/lightCurve/index.jsx, src/containers/LargeScaleStructurePlotContainer.jsx, yarn.lock
[EPO-2834]
Include an update to only show one toggle.
Range selected is within a one hundredth of the full data at a time.
Currently, returns just the selection.
=> [C] Use single toggle slider instead of dual toggle.

src/components/charts/galaxySelector/index.jsx, src/components/charts/lightCurve/Point.jsx, src/components/charts/lightCurve/index.jsx, src/components/page/blocks/blocksUtilities.js, src/components/qas/questions/Prompt.jsx, src/components/qas/questions/prompt.module.scss, src/components/qas/questions/qaExpansionList/styles.module.scss, src/components/qas/styles.module.scss, src/containers/WithQAing.jsx, src/data/pages/acquiring-the-data-1-1.json, src/data/pages/blinking-supernovae.json, src/data/pages/discovering-supernovae.json, src/data/pages/discuss-report.json, src/data/pages/distance-to-supernovae-1-3.json, src/data/pages/interpreting-hubble-plot-1.json, src/data/pages/observing-supernovae.json, src/data/pages/searching-for-supernovae-1.json, src/data/pages/searching-for-supernovae-2.json, src/data/pages/searching-for-supernovae-3.json
bug Fix: GalaxySelector answers persist between pageloads;
Stores answers in accordion for more immediate selection success feedback;
Updates/Implements across all investigations;
Minor QA style updates;
=> [EPO-2887] Galaxy&SupernovaSelectors use accordion QAs

src/data/pages/interpreting-hubble-plot-3.json, src/data/pages/testing-law.json, static/data/galaxies/scrambler-2.json
Updates Expanding Universe page **interpreting-a-hubble-plot-3/** to indicate to the user that they can find the details they're asked about in each point in the Hubble Plot's tooltip
=> [EPO-2829] Update Expanding Universe page copy and data to refer to galaxies by numbered designations (as opposed to their true names)

src/components/charts/hubblePlot/HubblePlot2D.jsx, src/components/charts/hubblePlot/Trendline.jsx, src/containers/HubblePlot2DContainer.jsx
This supplants previous hover & click UI;
Clear button clears hubble constant answer and associated trendline;
Includes fix to correctly place the trendline from hubbleConstant when slope was very small;
=> [EPO-2896] HubblePlot trendline supports click & drag

src/components/charts/hubblePlot/hubble-plot.module.scss, src/components/charts/shared/navDrawer/nav-drawer.module.scss
=> Larger Menu & Buttons Now Use a Default Grey Color

src/data/pages/discuss-report.json, src/data/pages/distance-to-supernovae-3.json
The values in the tables changed from either million ly or ly to Mly.
=> Table Values Changed to Mly

package.json, src/components/page/blocks/WidgetBlock.jsx, src/components/visualizations/orbitalViewer/Camera.jsx, src/components/visualizations/orbitalViewer/CameraController.jsx, src/components/visualizations/orbitalViewer/Orbital.jsx, src/components/visualizations/orbitalViewer/index.jsx, src/components/visualizations/orbitalViewer/orbitalUtilities.js, src/components/visualizations/shared/Box.jsx, src/containers/OrbitalViewerContainer.jsx, src/data/pages/threejs-test.json, yarn.lock
Not optimized for performance;
Not using real start point;
Not using real inclination;
Not uniformly scaled (in time or position)
=> [EPO-2928] Add POC OrbitalViewer

src/components/charts/galaxySelector/blinker/BlinkerControls.jsx, src/components/charts/galaxySelector/blinker/BlinkerImages.jsx, src/components/charts/galaxySelector/blinker/blinker.test.js, src/components/charts/galaxySelector/blinker/index.jsx, src/components/charts/galaxySelector/index.jsx, src/components/charts/galaxySelector/legend/index.jsx, src/components/charts/galaxySelector/legend/legend.test.js, src/components/site/forms/table/index.jsx, src/components/site/forms/table/table.test.js, src/components/site/forms/textField/textField.test.js
Includes unit testing for SupernovaSelector, Legend, and Blinker
Includes minor refactor of Blinker components
=> [EPO-2924] Add tests for SupernovaSelector sub-components

src/components/charts/galaxiesPosition3D/galaxies-position-3D.module.scss, src/components/charts/galaxiesPosition3D/index.jsx, src/components/charts/galaxySelector/blinker/blinker.test.js, src/components/charts/hubblePlot/Points.jsx, src/components/charts/hubblePlot/hubblePlot.test.js, src/components/charts/hubblePlot/index.jsx, src/components/charts/shared/Tooltip.jsx, src/components/widgets/widgets-utilities.js, src/containers/GalaxiesPosition3DContainer.jsx, src/containers/GalaxyScramblerContainer.jsx, src/containers/GalaxySelectorContainer.jsx, src/containers/HubblePlotContainer.jsx, src/lib/utilities.js
Does not include tests for generating hubble plot points
=> [EPO-2986] Tests basic hubblePlot interactivity

src/components/visualizations/orbitalViewer/Orbital.jsx, src/components/visualizations/orbitalViewer/OrbitalDetails.jsx, src/components/visualizations/orbitalViewer/index.jsx, src/containers/OrbitalViewerContainer.jsx
Details presented in table;
Properties presented in details include name, eccentricity, inclination, semi-major axis, and absolute magnitude
=> [EPO-2974] Add active object details to OrbitalViewer

src/assets/stylesheets/STACSS/_appearance.scss, src/assets/stylesheets/_variables.scss, src/components/charts/galacticProperties/LegendMultiple.jsx, src/components/charts/galacticProperties/galactic-properties.module.scss, src/components/charts/galacticProperties/index.jsx, src/components/charts/galaxySelector/Point.jsx, src/components/charts/galaxySelector/Points.jsx, src/components/charts/galaxySelector/galaxy-selector.module.scss, src/components/charts/galaxySelector/index.jsx, src/components/charts/histogram/LegendMultiple.jsx, src/components/charts/histogram/index.jsx, src/components/charts/hubblePlot/Points.jsx, src/components/charts/hubblePlot/hubble-plot.module.scss, src/components/charts/hubblePlot/index.jsx, src/components/charts/shared/navDrawer/StarAvatar.jsx, src/components/charts/sizeDistancePlotter/LegendMultiple.jsx, src/components/charts/sizeDistancePlotter/index.jsx, src/components/charts/sizeDistancePlotter/size-distance-plotter.module.scss, src/containers/GalaxyScramblerContainer.jsx, src/containers/GalaxySelectorContainer.jsx, src/lib/utilities.js
Supplants previous reliance on colors defined per data set in json data;
Works in all cases except precipitating colors across pages, that still has to happen in the data: in this case graceful fallback is provided
=> [EPO-2995] Apply colors to plot in presence of multiple flag

gatsby-node.js, src/components/pageNav/index.jsx, src/components/site/progress/index.jsx, src/components/site/progress/progress.module.scss, src/components/site/tableOfContents/index.jsx, src/components/site/tableOfContents/table-of-contents.module.scss, src/containers/EndingContainer.jsx, src/layouts/index.jsx, src/lib/utilities.js, src/state/GlobalStore.js
Includes updates to TOC and Progress tracking component
=> [EPO-3018] Add "end" page to investigation flow

src/components/charts/histogram/LegendMultiple.jsx, src/components/charts/histogram/histogram.module.scss, src/components/charts/histogram/index.jsx
In presence of multiple flag NavDrawer allows for toggling individual histograms on/off within one plot
=> [EPO-3043] Histogram supports plot toggling

src/data/pages/discuss-report.json, src/data/pages/distance-to-supernovae-3.json, src/data/pages/expand-discuss-report.json, src/data/pages/expand-summary.json, src/data/pages/lsst-hubble-plot-2.json, src/data/pages/object-composition-1.json, src/data/pages/observable-summary.json, src/data/pages/solar-system-discuss-report.json, src/data/pages/solar-system-summary-1.json, src/data/pages/solar-system-summary-2.json, src/data/pages/solar-system-summary-3.json, src/data/pages/solar-system-summary-4.json, src/data/pages/solar-system-summary-5.json, src/data/pages/solar-system-summary.json, src/data/pages/summary.json
Use updated language for these pages that appear in every investigation
=> [EPO-3109] Update summary and discuss + report titles

src/components/charts/timeDomainViewer/Point.jsx, src/components/charts/timeDomainViewer/index.jsx, src/containers/TimeDomainViewerContainer.jsx, src/containers/WithQAing.jsx
To test you would need to create a accordion style question with an neo accessor type, then assign that question's id to the `togglePointsVisability` option.  The preselected option on the TImeDomainViewer must also NOT be set to true.
=> [EPO-3152] TimeDomainViewer objects are selectable

src/data/pages/lsst-hubble-plot.json
=> Text Input Changed to Select Options

src/components/charts/galaxySelector/Point.jsx, src/components/charts/shared/blinker/BlinkerImages.jsx, src/components/qas/questions/qaTextInput/index.jsx
Includes minor uipdate to GalaxySelector lazy loading
=> [EPO-3096] Update galaxy #2 pos on /interpreting-a-hubble-plot-1

src/components/charts/histogram/XAxis.jsx, src/components/charts/histogram/YAxis.jsx, src/components/charts/histogram/histogram.module.scss, src/components/charts/largeScaleStructure/large-scale-structure-plot.module.scss, src/components/qas/index.jsx, src/components/qas/questions/qaSelect/index.jsx, src/data/pages/change-over-time-4.json
Inlcudes minor stylistic updates to related components;
Includes minor fix to QA keys and QASelect inline variant;
=> [EPO-3114] Improved nav layout in LargeScaleStruct & Histogram

src/components/charts/largeScaleStructure/LargeScaleStructure2D.jsx, src/data/pages/change-over-time-1.json
[EPO-3163]
Make page with LSSW a SingleCol and position widget on bottom
Add ability to zoom into graph keeping current view as greatest top view.
=> [EPO-3163] Minor layout and functionality updates to LSSW

src/components/qas/questions/qaCalculators/shared/equation/FindDiameter.jsx, src/components/qas/questions/qaCalculators/shared/equation/equation.module.scss, src/components/qas/questions/qaCalculators/sizeCalculator/index.jsx, src/components/qas/questions/qaCalculators/sizeCalculator/sizeCalculator.module.scss
[EPO-3161]
Calculator will render only one generic label and show proper active
states.
=> [EPO-3161] Render label prop as label for whole SizeCalc instead of hardcoded labels on individual inputs

src/components/qas/questions/qaCalculators/distanceCalculator/index.jsx, src/components/qas/questions/qaCalculators/kineticEnergyCalculator/index.jsx, src/components/qas/questions/qaCalculators/sizeCalculator/index.jsx, src/containers/GalaxiesSelectorContainer.jsx, src/data/pages/determining-orbits-6.json
[C] Add lodash's debounce method in QACalcs
[EPO-3039]
Import lodash debounce method into 3 QACal files
Create new debounce functions for custom methods
Call new debounce function in debounce() with a 500ms delay
=> [EPO-3039] Add lodash's debounce method in QACalcs

src/components/visualizations/orbitalViewer/Camera.jsx, src/components/visualizations/orbitalViewer/CameraController.jsx, src/components/visualizations/orbitalViewer/index.jsx, src/containers/OrbitalViewerContainer.jsx, src/data/pages/close-to-earth-1.json, src/data/pages/close-to-earth-2.json, src/data/pages/close-to-earth-3.json, src/data/pages/close-to-earth-4.json, src/fragments/widgetOptions.js
Includes implementation in known use cases across Hazardous Asteroids investigation pages
=> [EPO-3160 & EPO-3158] OrbitalViewer force fixed POV & paused variants

src/components/charts/shared/unit/index.jsx, src/components/charts/shared/unit/utilities.js, src/components/qas/QA.jsx, src/components/qas/questions/qaCalculators/VolumeCalculator/index.jsx, src/components/qas/questions/qaCalculators/VolumeCalculator/volumeCalculator.module.scss, src/components/qas/questions/qaCalculators/shared/equation/FindVolume.jsx, src/components/qas/questions/qaCalculators/shared/equation/index.jsx, src/containers/WithQAing.jsx, src/data/pages/haz-summary-1.json, src/lib/utilities.js
Create new VolumeCalculator
Set up proper formatted value into table
Store data from calculator utilizing established structure
=> [EPO-3050] Add a volume calculator

src/data/pages/brightness-color-distance.json, src/data/pages/exploring-the-deep.json
=> [EPO-3223] Update copy

src/components/page/SingleCol.jsx, src/components/page/blocks/ImageBlock.jsx, src/components/page/page.module.scss, src/data/pages/cosmological-principle.json
[C] Add new layout position "middle" param for correctly layout adjustment.
=> [EPO-3224] Update copy and layouts

src/components/charts/hubblePlot/CursorPoint.jsx, src/components/charts/hubblePlot/hubble-plot.module.scss, src/components/charts/hubblePlot/index.jsx
=> [EPO-3095] Ghost Point On Cursor For HubblePlot

src/components/charts/galaxySelector/index.jsx, src/containers/GalaxySelectorContainer.jsx, src/data/pages/distance-to-supernovae-3.json
=> Clear Button Removes Points

src/containers/WithQAing.jsx, src/data/pages/haz-summary.json
Designated accessor was pointing to and incorrect index. Update pointer
and index to read more clearly.
=> [EPO-3237] SizeCalculator correctly populates table cells with answers

src/components/qas/QA.jsx, src/components/qas/questions/qaCalculators/VolumeCalculator/index.jsx, src/components/qas/questions/qaCalculators/distanceCalculator/distanceCalculatorUtilities.js, src/components/qas/questions/qaCalculators/distanceCalculator/index.jsx, src/components/qas/questions/qaCalculators/kineticEnergyCalculator/index.jsx, src/components/qas/questions/qaCalculators/massCalculator/index.jsx, src/components/qas/questions/qaCalculators/shared/equation/FindDiameter.jsx, src/components/qas/questions/qaCalculators/shared/equation/FindDistanceModulus.jsx, src/components/qas/questions/qaCalculators/shared/equation/FindKineticEnergy.jsx, src/components/qas/questions/qaCalculators/shared/equation/FindMass.jsx, src/components/qas/questions/qaCalculators/shared/equation/FindParsecs.jsx, src/components/qas/questions/qaCalculators/shared/equation/FindVolume.jsx, src/components/qas/questions/qaCalculators/sizeCalculator/index.jsx, src/components/qas/questions/qaCalculators/volumeCalculator/index.jsx, src/components/qas/questions/qaCalculators/volumeCalculator/volumeCalculator.module.scss
Includes remove logic of returning either value or string from equations
Equations now return null if no value is present
Equations check input value for null
Equation Components (rendered view) to handle value or 'variable' render
=> [EPO-2970] Correct variable type passing

src/components/pageNav/index.jsx, src/components/site/button/styles.module.scss, src/containers/PageContainer.jsx, src/data/pages/universe-through-time.json, src/fragments/question.js
Unanswered questions or empty answers prevent page progression.
=> [C] Prevents Page Progression

src/components/charts/asteroidClass/index.jsx, src/components/charts/lightCurve/Template.jsx, src/components/charts/shared/observationsTables/ObservationsTable.jsx, src/components/site/forms/table/index.jsx, src/components/site/forms/table/table.module.scss, src/data/pages/characterizing-comet.json, src/data/pages/characterizing-mba.json, src/data/pages/characterizing-neo.json, src/data/pages/characterizing-orbits-4.json, src/data/pages/characterizing-tno.json, src/data/pages/classifying-objects-1.json, src/data/pages/classifying-objects-2.json, src/data/pages/identifying-groups-1.json, src/data/pages/identifying-groups-2.json, src/data/pages/identifying-groups-3.json, src/data/pages/identifying-groups-4.json, src/data/pages/identifying-groups.json, src/fragments/table.js
Cells will update to be the same width % by number cols
=> [EPO-3112] Update table cell to be the same width %

src/data/pages/distance-to-supernovae-1-1.json, src/data/pages/distance-to-supernovae-1-2.json, src/data/pages/distance-to-supernovae-1.json, src/data/pages/interpreting-hubble-plot-1.json
<p> tags are not needed for this question
=> [EPO-3282] Remove the <p> tags from inside the JSON

src/components/charts/hubblePlot/hubblePlot.test.js, src/components/charts/lightCurve/index.jsx, src/components/charts/lightCurve/light-curve.module.scss, src/components/charts/lightCurve/lightCurve.test.js
Tests rendering and point interactions;
Does not include tests for interactable templates or peak magnitude selection;
=> [C] LightCurve has tests

src/components/visualizations/orbitalViewer/PlaybackSpeed.jsx, src/components/visualizations/orbitalViewer/index.jsx, src/components/visualizations/orbitalViewer/orbital-viewer.module.scss
Textual indicator of current playback speed is shown in the top right corner: relative to real life speed of time...
=> [EPO-3361] OrbitViewer has playback speed descriptions

src/components/page/page.module.scss, src/data/pages/detecting-objects.json, static/data/neos/tno120132.json
Updates TNO dataset for DoubleTimeDomainViewer, implements that data, and includes minor stylistic update to normalize spacing between main page layout components (tables, copy, questions, widgets, etc)
=> [C] Implement updated TimeDomainViewer data

src/data/pages/determining-orbits-1.json, src/data/pages/determining-orbits-1a.json, src/data/pages/determining-orbits-2.json, src/data/pages/determining-orbits.json
slight modifications to the "Determining Orbits" section of the investigation in terms of what content & questions divided amongst those pages.
=> [EPO-3360] Update Hazardous Asteroids page sequencing/content

src/components/charts/shared/unit/index.jsx, src/components/charts/shared/unit/utilities.js, src/components/qas/questions/qaCalculator/equations/FindImpactCrater.jsx, src/components/qas/questions/qaCalculator/equations/equations.module.scss, src/components/qas/questions/qaCalculator/index.jsx, src/components/qas/questions/qaCalculator/qaCalculator.module.scss, src/components/qas/questions/qaCalculator/qaCalculatorUtilities.js, src/components/qas/questions/qaCalculator/qaCalculatorsData.jsx, src/components/qas/questions/qaCalculator/tests/ImpactCalculator.test.js, src/data/pages/haz-summary-2.json, src/lib/utilities.js
Add crater depth calcuator (values are calculating incorrectly)
Add richtor magnitude calculator
Add seismic damage textual output
Add air blast calculator (needs much more work)
Add textual output for air blast damage
Create ticket for the additional work not finish in this ticket.
Work finalized in this ticket.
=> [EPO-3408] Added additional calculators and textual outputs

src/components/qas/questions/qaCalculator/equations/FindImpactCrater.jsx, src/components/qas/questions/qaCalculator/qaCalculatorUtilities.js
Organize descriptions by category within their damage ranges
Use Lodash's 'find' function to pull out first found in array
Push all responses into array and print them on screen
=> [EPO-3502] Update AirBlast descriptions

src/components/charts/prismWidget/index.jsx, src/components/charts/prismWidget/prism-widget.module.scss, src/components/site/selectField/index.jsx, src/components/site/selectField/styles.module.scss, src/components/widgets/widgets-utilities.js, src/containers/PrismWidgetContainer.jsx, src/data/pages/how-filters-work.json
=> [F] Prism Widget

src/components/charts/prismWidget/index.jsx, src/components/charts/prismWidget/prism-widget.module.scss, src/components/site/slider/index.jsx, src/data/pages/coloring-putting-it-all-together.json, src/data/pages/how-filters-work.json, src/data/pages/types-of-light.json
[C] Update pages according to notes provided from Ardis
Fix Page 4 question layout to reflect a/b answer type (compoundInput)
Add ColorTool to Page 18
Add missing image to Page 2
Fix css: remove vendor prefixes and !important statements
=> [EPO-3564] Begin cleaning up Coloring the Universe code

src/data/pages/astronomical-color-image.json, src/data/pages/color-in-astronomical-images.json, src/data/pages/coloring-reflect-and-discuss.json, src/data/pages/colorizing-the-images.json, src/data/pages/construct-a-color-image.json, src/data/pages/constructing-with-three-filters.json, src/data/pages/eyes-vs-telescopes.json, src/data/pages/rubin-lsst-camera-filters.json, src/data/pages/types-of-light.json, src/data/pages/uses-of-astronomical-filters.json
=> [EPO-3594] Update layout to better match expectations in doc

src/components/qas/questions/qaCalculator/index.jsx, src/components/qas/questions/qaCalculator/qaCalculatorsData.jsx
If min/max value is present and user input is beyond either values, respectively, then forcefully update to either min or max value.
=> [EPO-3501] Add min/max checks and update accordingly

src/components/charts/shared/StellarValue.jsx, src/components/qas/questions/qaCalculator/equations/FindImpactCrater.jsx, src/components/qas/questions/qaCalculator/qaCalculatorUtilities.js, src/components/qas/questions/qaCalculator/tests/ImpactCalculator.test.js, src/data/pages/haz-summary-2.json, src/lib/utilities.js
Updates ImpactCalc answerData structure;
Updates pageData for Hazardous Asteroids page where ImpactCalc is implemented to render updated answer values in associated tables;
Removes duplicate info from ImpactCalc now that it's available to be shown in associated tables
=> [EPO-3694] Update ImpactCalc answers rendered in tables

src/components/charts/shared/StellarValue.jsx, src/components/charts/shared/observationsTables/ObservationsTable.jsx, src/components/charts/shared/unit/index.jsx, src/components/charts/shared/unit/utilities.js, src/components/qas/questions/qaCalculator/equations/FindImpactCrater.jsx, src/components/qas/questions/qaCalculator/tests/ImpactCalculator.test.js, src/lib/utilities.js
Presentational only: math done with "real" numbers (i.e. not rounded);
Includes values in the calc itself, and where they are used from answer calc outputs;
=> [EPO-3684] ImpactCalc values rounded to 3 sig figs

src/components/charts/shared/StellarValue.jsx, src/components/qas/questions/qaCalculator/equations/FindDiameter.jsx, src/components/qas/questions/qaCalculator/equations/FindDistanceModulus.jsx, src/components/qas/questions/qaCalculator/equations/FindImpactCrater.jsx, src/components/qas/questions/qaCalculator/equations/FindKineticEnergy.jsx, src/components/qas/questions/qaCalculator/equations/FindParsecs.jsx, src/components/qas/questions/qaCalculator/index.jsx, src/components/qas/questions/qaCalculator/qaCalculatorUtilities.js, src/components/qas/questions/qaCalculator/tests/SizeCalculator.test.js, src/lib/utilities.js
Includes updates to components that render calculated values based on user input to similarly handle 0, negative, and Infinite values;
Includes support for entering and calculating with decimals in the form "0.12345" as well as ".12345";
=> [EPO-3681] Calc inputs handle 0, neg, and Infinity vals

src/components/charts/shared/StellarValue.jsx, src/components/charts/shared/unit/index.jsx, src/components/charts/shared/unit/utilities.js, src/components/qas/questions/qaCalculator/equations/FindDiameter.jsx, src/components/qas/questions/qaCalculator/equations/FindImpactCrater.jsx, src/components/qas/questions/qaCalculator/equations/FindKineticEnergy.jsx, src/components/qas/questions/qaCalculator/qaCalculatorUtilities.js, src/components/qas/questions/qaCalculator/qaCalculatorsData.jsx, src/components/qas/questions/qaCalculator/tests/ImpactCalculator.test.js, src/components/qas/questions/qaCalculator/tests/SizeCalculator.test.js, src/lib/utilities.js
Uses meters presentationally and for all applicable math;
Math dependent on unit specific constants and operations use properly converted values (i.e. honor existing units);
Fixes some minor rounding problems;
=> [EPO-3693] Size & Impact Calcs use meters NOT kms

src/components/charts/colorMixingTool/color-tool.module.scss, src/components/charts/colorMixingTool/color-tool.utilities.js, src/components/charts/colorMixingTool/index.jsx, src/components/charts/prismWidget/prism-widget.module.scss, src/containers/AstroToolContainer.jsx, src/data/pages/what-should-my-image-look-like.json, src/fragments/widgetOptions.js, static/data/filters/m33-filter.json, static/data/filters/m63-filter.json, static/data/filters/new-data-astro-filter.json
Includes copy and layout updates to page 17
Includes update to json data and allow buttons to have either upper or lowercase
=> [EPO-3827] Add boolean to ColorTool to show controls or image

src/components/charts/prismWidget/index.jsx, src/components/charts/prismWidget/prism-widget.module.scss, src/components/qas/questions/qaMultiSelect/qaMultiSelect.module.scss, src/containers/PrismWidgetContainer.jsx, src/data/pages/how-filters-work.json
Initial setup
[F] Prism Tool to save selected color and add labels
Includes:
- Add label to 'filter'
- Add label to color select
- Prism Tool can store selected color when questionId present
=> [EPO-3828] Prism widget will store answer

src/data/pages/object-composition-1.json, src/data/pages/solar-system-discuss-report.json
Add Orbit viewer to reflect-and-discuss from object-composition-1
Add table with answers from object-composition-1 to reflect-and-discuss
=> [EPO-3488] Add widget and table to reflect-and-discuss

src/components/charts/shared/navDrawer/nav-drawer.module.scss
EPO-3409 - Templates NavDrawer overlap plot bug
=> [B] Added Padding to NavDrawerContent

src/components/charts/hubblePlot/hubble-plot.module.scss, src/components/charts/hubblePlot/index.jsx, src/data/pages/interpreting-hubble-plot-3.json, src/data/pages/interpreting-hubble-plot-5.json, src/lib/utilities.js
In the Hubble Plot, when there aren't points selected on the galaxy selector and the hubble plot is hidden, a message displays.
=> [F] Added Message to Hidden Widgets

src/containers/HubblePlotContainer.jsx
=> [EPO3097] Fixed Adjustable Trendline 

src/components/charts/lightCurve/index.jsx, src/containers/AsteroidClassContainer.jsx, src/containers/AsteroidClassTwoUpContainer.jsx, src/containers/OrbitalViewerContainer.jsx
Fixed overlap problem on light curve and found that other files were using an undefined class.
EPO-3409
=> [B] Replaced PaddingDrawerInner for useless main content class

src/components/visualizations/orbitalViewer/orbital-viewer.module.scss
=> [F] Resize OrbitViewer on Smaller Screens

src/components/charts/histogram/index.jsx
=> [B] Added OffsetTop to Histogram Y Axis

src/components/charts/histogram/index.jsx, src/components/charts/lightCurve/index.jsx, src/components/charts/shared/navDrawer/index.jsx, src/containers/GalaxiesFilterSelectorContainer.jsx, src/containers/GalaxySelectorContainer.jsx, src/containers/SupernovaSelectorWithLightCurveContainer.jsx
=> [F] Replaced ShowNavDrawer with  Conditional Wrappers

src/components/charts/lightCurve/Template.jsx
You can now scale the light curve template as small as you want
EPO-2712
=> [B] Scale LightCurve Template Down

src/components/charts/hubblePlot/Points.jsx, src/components/charts/hubblePlot/hubble-plot.module.scss, src/components/charts/hubblePlot/index.jsx
=> [C] Made Hubble Points Translucent & Outlined

src/data/pages/coloring-acknowledgements.json, src/data/pages/coloring-reflect-and-discuss.json, src/data/pages/expand-summary.json, src/data/pages/expanding-acknowledgements.json, src/data/pages/exploding-acknowledgements.json, src/data/pages/haz-acknowledgements.json, src/data/pages/haz-reflect-discuss.json, src/data/pages/milky-way-acknowledgements.json, src/data/pages/milky-way-introduction.json, src/data/pages/observable-acknowledgements.json, src/data/pages/observable-summary.json, src/data/pages/solar-system-acknowledgements.json, src/data/pages/solar-system-summary-5.json, src/data/pages/summary.json, src/data/pages/window-stars-acknowledgements.json, src/data/pages/window-stars-introduction.json
=> [F] Added Acknowledgement Pages

src/components/site/tableOfContents/table-of-contents.module.scss
Utilize positioning of the TOC and apply a media query to catch screen size changes.
=> [EPO-4024] Fix TOC overflow hidden issue

gatsby-node.js, src/components/pageNav/index.jsx, src/components/qas/answers/ExpansionPanel.jsx, src/components/qas/answers/FormattedAnswer.jsx, src/components/qas/questions/Prompt.jsx, src/components/qas/questions/qaCalculator/CalculatedMeasurement.jsx, src/components/qas/questions/qaCalculator/equations/FindDiameter.jsx, src/components/qas/questions/qaCalculator/equations/FindDistanceModulus.jsx, src/components/qas/questions/qaCalculator/equations/FindImpactCrater.jsx, src/components/qas/questions/qaCalculator/equations/FindImpactDamage.jsx, src/components/qas/questions/qaCalculator/equations/FindImpactEnergy.jsx, src/components/qas/questions/qaCalculator/equations/FindKineticEnergy.jsx, src/components/qas/questions/qaCalculator/equations/FindMass.jsx, src/components/qas/questions/qaCalculator/equations/FindParsecs.jsx, src/components/qas/questions/qaCalculator/equations/equations.module.scss, src/components/qas/questions/qaCalculator/index.jsx, src/components/qas/questions/qaExpansionList/QAExpansionPanel.jsx, src/components/qas/questions/qaMultiSelect/index.jsx, src/components/qas/questions/qaSelect/index.jsx, src/components/qas/questions/qaTextInput/index.jsx, src/components/qas/styles.module.scss, src/components/site/header/header.module.scss, src/containers/QAReviewContainer.jsx
JIRA: https://jira.lsstcorp.org/browse/EPO-4351
This new page allows for the teachers and students to review all answers within the investigation. This will also allow for the eventual printability of this page.
There are many places that I've touched within this branch. I've added a few new classes within the `questions/styles.module.scss` that apply some styling that the question labels were creating. I had to do this in order to keep the flow of the investigations as is. This required me to dive into each question component and adjust the code in order to render the proper html element on the QA Review page. I've also made sure that this change did not affect the way the questions were rendering and functioning in the investigation.
Also, a heads up, I had to use `!important` within …
=> [EPO-4351] Add QA Review page

src/containers/PageContainer.jsx
JIRA: https://jira.lsstcorp.org/browse/EPO-4401
Switched the login of required questions to "ALL" required by removing the `required` catch. Works pretty seamlessly with the logic already in place (work done by Parker).
This was a quick change. I've left in the `required` flag in `PageContainer` in case we want to provide a way to _not_ required a specific question, but the logic for that isn't baked yet.
Include an indication of how detailed a review you want on a 1-10 scale. **2 = "I barely need review on this, but just a quick glance."**
Tested by trying to advance forward without answering all the questions on the page. For now, the arrow at the bottom is the only restriction in advancing forward...TOC restrictions to come next.
=> [C] All questions required

src/components/site/icons/Replay.jsx, src/components/site/slider/index.jsx, src/components/visualizations/orbitalViewer/CameraController.jsx, src/components/visualizations/orbitalViewer/PlaybackSpeed.jsx, src/components/visualizations/orbitalViewer/controls/controls.module.scss, src/components/visualizations/orbitalViewer/controls/index.jsx, src/components/visualizations/orbitalViewer/index.jsx, src/components/visualizations/orbitalViewer/orbital-viewer.module.scss
JIRA: https://jira.lsstcorp.org/browse/EPO-4472
This change utilizes José's designs to restyle the OrbitViewer controls for a cleaner and clearer UX/UI. Added a 'non-working' zoom reset button to match José's design. Used the SelectionControlGroup component with `type="radio"` to then mimic a slider control.
Added a "placeholder" handler to 'empty' function to set-up for the "zoom-reset" functionality. Added two new svg's for this and 'mocked' a slider. I attempted using the react-md slider, but when I `transform: rotate(90degs);` this caused a weird bug that only allowed the slide to be manipulated by dragging left-to-right no up-and-down as expected.
Include an indication of how detailed a review you want on a 1-10 scale:  5 = "Please make sure there are no obvious errors and that you …
=> [EPO-4472] Restyle OrbitViewer controls

src/components/visualizations/orbitalViewer/Orbital.jsx, src/components/visualizations/orbitalViewer/Orbitals.jsx, src/components/visualizations/orbitalViewer/index.jsx, src/components/visualizations/orbitalViewer/orbital-viewer.module.scss, src/containers/QAReviewContainer.jsx, src/data/pages/characterizing-comet.json, src/data/pages/characterizing-mba.json, src/data/pages/characterizing-neo.json, src/data/pages/characterizing-tno.json, src/data/pages/classifying-objects-1.json, src/data/pages/classifying-objects-2.json, src/data/pages/classifying-objects.json, src/data/pages/detecting-objects.json, src/data/pages/identifying-groups-1.json, src/data/pages/identifying-groups-2.json, src/data/pages/identifying-groups-3.json, src/data/pages/identifying-groups-4.json, src/data/pages/identifying-groups.json, src/data/pages/solar-system-summary-1.json, src/data/pages/solar-system-summary-2.json, src/data/pages/solar-system-summary-5.json, src/data/pages/solar-system-summary-6.json, src/data/pages/solar-system-summary.json, src/fragments/widgetOptions.js
Includes minor fix to OrbitViewer to conditionally label objects in the viewer
JIRA: https://jira.lsstcorp.org/browse/<ID>
A few sentences describing the outcome of the change (“fixes a thing”; "adds the stuff") and how you tackled it (“added a prop to prevent lazyloading in the presence of barbara walters”).  How successful is the change?  And how are you measuring that success?
Where should the reviewer look for the change?  Do they review the change on the frontend?  How extensive is the change?  Does it affect Components used in a variety of contexts?  Anything you'd like reviewers to pay particular attention to or questions you have about the change.
- 5 = "Please make sure …
=> [C] Update print/QAReview options for Solar System Widgets & Tables

gatsby-browser.js, src/components/charts/colorMixingTool/index.jsx
JIRA: https://jira.lsstcorp.org/browse/EPO-4604
Changes include minor updates to coloring the universe investigation.
Color tool update was made to fix and empty heading.
Include an indication of how detailed a review you want on a 1-10 scale: - 1 = "I barely need review on this"
n/a
=> [EPO-4604] Cross-Browser test Coloring the Universe

src/data/pages/coloring-acknowledgements.json
JIRA: https://jira.lsstcorp.org/browse/EPO-4606
Add acknowledgements content per Lauren's update.
n/a
Include an indication of how detailed a review you want on a 1-10 scale. - 1 = "I barely need review on this"
n/a
=> [EPO-4606] Add content to Acknowledgements page per Lauren

src/components/pageNav/index.jsx, src/containers/PageContainer.jsx
JIRA: https://jira.lsstcorp.org/browse/EPO-4668
This change now checks for when then compoundQuestion type is present. Then the shouldDisable method checks all questions and their answers and returns true or false depending on that evaluation.
n/a
Go to any compound question type and test all answers. Good page to test is /what-should-my-image-look-like/ in coloring the universe investigation.
=> [EPO-4668] `shouldDisable` now checks for compoundQuestion type

src/assets/stylesheets/_variables.scss, src/components/charts/galaxySelector/legend/legend.test.js, src/components/charts/lightCurve/lightCurve.test.js, src/components/charts/scatter-plot/index.jsx, src/components/charts/shared/blinker/blinker.test.js, src/components/site/button/button.test.js, src/components/site/card/card.test.js, src/components/site/forms/select/select.test.js, src/components/site/forms/table/table.test.js, src/components/site/forms/textField/textField.test.js, src/components/site/header/header.module.scss, src/components/site/header/header.test.js, src/components/visualizations/orbitalViewer/Ellipse3D.js
JIRA: https://jira.lsstcorp.org/browse/EPO-4657
This change adds colors from Design Doc and applies them to toolbars and chart points.
n/a
Include an indication of how detailed a review you want on a 1-10 scale. - 1 = "I barely need review on this"
n/a
n/a
=> [EPO-4657] Add defined colors from Visual Design Doc

src/data/pages/characterizing-mba.json, src/data/pages/characterizing-neo.json, src/data/pages/characterizing-tno.json
For JIRA: "EPO-5701 #IN-REVIEW #comment Update pages 7-9"
JIRA: https://jira.lsstcorp.org/browse/EPO-5701
Update the definition of TNO for the dropdown questions on pages 7-9
Minimal change
Verify that the definition of TNO is updated in each of the dropdown questions (third option)
=> [C] Update StSS pg.7-9

src/data/pages/characterizing-comet.json, src/data/pages/characterizing-orbits-4.json, src/data/pages/identifying-groups-1.json, src/data/pages/identifying-groups-2.json, src/data/pages/identifying-groups-3.json, src/data/pages/identifying-groups-4.json, src/data/pages/identifying-groups-5.json, src/data/pages/identifying-groups.json
For JIRA: "EPO-5702 #IN-REVIEW #comment Add new page, update ordering"
JIRA: https://jira.lsstcorp.org/browse/EPO-5702
Changed the last TNO definition then moved page 17 to become the new page 12 and altered it's contents. Additionally re-numbered and updated links for the other "identifying groups" pages.
Review between pages 11 and 17 to verify ordering and content.
How did you test this change?  Can the reviewer test this change for themselves?
If you wrote new tests in the change it's fine to just put "New tests in PR". If you haven't added any tests but you think your change is covered by existing tests you can …
=> [C] New page between 11 and 12 in StSS

src/data/pages/characterizing-orbits-4.json
Add missing question to page 11
=> [C] Add missing question

src/data/pages/history-solar-system-1.json, src/data/pages/nebula-theory.json
JIRA: https://jira.lsstcorp.org/browse/EPO-5705
Content revisions to page 19, rephrasing and replacing questions.
Review page /nebula-theory/
- 3
Tested by going through investigation up to page 19 /nebula-theory/ and verifying the following page.
=> [C] EPO-5705

src/components/visualizations/orbitalViewer/Orbital.jsx, src/components/visualizations/orbitalViewer/Sun.jsx, src/components/visualizations/orbitalViewer/orbitalUtilities.js
JIRA: https://jira.lsstcorp.org/browse/EPO-5827
Adds utility constants to hold the orbital body and path colors
Some small updates to the Orbital Viewer sub-components 
- 2
Observe the orbital viewer and check that the orbital bodies and paths have been updated and display well.
=> [C] update orbital path colors

src/components/page/blocks/QuestionBlock.jsx, src/data/pages/history-solar-system.json, src/fragments/question.js, src/lib/utilities.js
For JIRA: "EPO-5885 #IN-REVIEW #comment add layout options to questions"
JIRA: https://jira.lsstcorp.org/browse/EPO-5885
Add the ability to provide a layout for individual questions 
For all pages except for /history-solar-system there should be no change to the question order. For /history-solar-system the question on the page should be moved to the bottom right. 
- 3
Test on frontend and observe that there is no visual change to questions apart from /history-solar-system where a question has been moved. Experiment with adding layout to individual questions. 
=> [C] Add layout options to questions

src/components/visualizations/orbitalViewer/Orbitals.jsx, src/components/visualizations/orbitalViewer/orbitalUtilities.js
For JIRA: "EPO-6047 #IN-REVIEW #comment add mars orbital path to viewer"
JIRA: https://jira.lsstcorp.org/browse/EPO-6047
Add orbital path of Mars to the investigations orbit viewer
Review changes by checking the orbit viewer on pages 13-16, 20-22, and 27. 
=> [C] Add Mars orbital path to viewer

src/data/pages/solar-system-summary-6.json
JIRA: https://jira.lsstcorp.org/browse/EPO-6050
Updates question ids such that no id is ever reused in the solar system investigation.
I'm pretty sure I spotted 'em all...
=> Solar System question ids are unique

src/data/pages/characterizing-comet.json, src/data/pages/characterizing-mba.json, src/data/pages/characterizing-neo.json, src/data/pages/characterizing-tno.json
For JIRA: "EPO-6055 #IN-PROGRESS #comment Add values to characterizing tables"
JIRA: https://jira.lsstcorp.org/browse/EPO-6055
Add the values from the question labels to the `value` field so they display in the table that persists through the questions
Make sure to clear local storage before testing.
=> [C] Add values to characterizing tables

src/data/pages/inclination.json
For git: "Resolves EPO-6054"
For JIRA: "EPO-6054 #IN-REVIEW #comment update inclination with video"
JIRA: https://jira.lsstcorp.org/browse/EPO-6054
Update StSS inclination with new video, layout, and text
Test by viewing /inclination/ page
=> [C] update inclination with new video and text

src/containers/GalaxiesSelectorContainer.jsx, src/containers/OrbitalViewerContainer.jsx, src/containers/QAReviewContainer.jsx, src/data/locales/en/widgets.json, src/data/pages/detecting-objects.json, src/data/pages/history-solar-system-1.json, src/data/pages/history-solar-system.json, src/data/pages/identifying-groups-1.json, src/data/pages/identifying-groups-4.json, src/data/pages/inclination.json, src/data/pages/nebula-theory.json, src/data/pages/solar-system-section-1.json, src/data/pages/solar-system-section-2.json, src/data/pages/solar-system-summary.json, src/state/GlobalStore.js
For git: "Resolves EPO-6186"
For JIRA: "EPO-6186 #IN-REVIEW #comment fix random source save"
JIRA: https://jira.lsstcorp.org/browse/<ID>
Grab bag of content revisions and some small bugs noted during pilot testing revision review
Compare with the list of issues noted in the JIRA ticket for EPO-6186
- 2
Review each change in the JIRA ticket and verify they are resolved. The random sources bug can be reviewed in both Surveying the Solar System and Observable Universe by checking that random sources are still selected and preserved correctly while also showing the progress checkmarks at the appropriate spot. Clear local storage before reviewing changes.
=> [C] content revisions and random sources fix

src/data/locales/en/solar-system.json, src/data/pages/characterizing-comet.json, src/data/pages/characterizing-tno.json, src/data/pages/orbital-interpretation-1.json
For JIRA: "EPO-6652 #IN-REVIEW #comment minor text updates"
JIRA: https://jira.lsstcorp.org/browse/EPO-6652
Make minor text updates to Surveying the Solar System
Compare against notes here: https://docs.google.com/document/d/1_PFyztx2n7KKYn1zM3TGxLCipUV0C8bWbDdyqBhWMxg/edit
=> [C] minor text updates

src/data/locales/es/astronomy.json, src/data/locales/es/interface.json, src/data/locales/es/solar-system.json, src/data/locales/es/widgets.json
JIRA: https://jira.lsstcorp.org/browse/EPO-6889
Add Spanish language translations to Surveying the Solar System investigation
Should note this will also have minor UI translations for other investigations.
Load Surveying the Solar System and switch to Spanish language.
=> [C] Spanish language translations

package.json, src/components/site/exportAnswers/index.jsx, src/containers/QAReviewContainer.jsx, src/containers/WithQAing.jsx, src/data/locales/en/expanding-universe.json, src/data/locales/en/interface.json, src/lib/answers.js, src/lib/utilities.js, yarn.lock
JIRA: https://jira.lsstcorp.org/browse/EPO-6894
Add an exporter for student answers to download in XLSX format with student answers shown on a single row
Review in frontend, change is mostly localized to new exporter but some of the answer formatters have been pulled out of the `WithQAing` HOC and into a utilities lib
- 3
Complete Expanding Universe or Surveying the Solar System and select the new "download answers" option at the end of the review page
=> [C] add XLSX export

src/data/investigations/investigations.json, src/data/pages/expand-discuss-report.json, src/data/pages/expand-summary.json, src/data/pages/expanding-universe-section-1.json, src/data/pages/interpreting-hubble-plot-3.json, src/data/pages/interpreting-hubble-plot-4.json, src/data/pages/interpreting-hubble-plot-5.json, src/data/pages/lsst-hubble-plot.json, src/data/pages/testing-law.json, src/data/pages/universe-through-time.json, src/data/pages/using-evidence.json
For JIRA: "EPO-7071 #IN-REVIEW #comment content revisions"
JIRA: https://jira.lsstcorp.org/browse/EPO-7071
3rd round of content revisions for Expanding Universe, includes pages:
- New section break (/section-1)
- interpreting-a-hubble-plot-4
- interpreting-a-hubble-plot-5
- testing-law
=> [C] expanding universe content revisions

src/components/qas/questions/qaMultiSelect/index.jsx, src/data/locales/en/expanding-universe.json
Fix a typo and add translation to multi-select placeholders
=> [C] tiny tweaks
