lsst-epo/investigation-static

src/assets/stylesheets/_variables.scss, src/assets/stylesheets/components/charts/_svg.scss, src/components/charts/galaxySelector/blinker/blinker.module.scss, src/components/charts/galaxySelector/galaxy-selector.module.scss, src/components/qas/questions/qaCalculators/distanceCalculator/distanceCalculator.module.scss
Scales width of graph based on available screen height, up to a point: minimum of 420px
=> [EPO-2739] Galaxy/SupernovaSelectors scale to screen height

src/components/charts/galacticProperties/Point.jsx, src/components/charts/galacticProperties/Points.jsx, src/components/charts/galacticProperties/index.jsx, src/components/charts/galaxySelector/Point.jsx, src/components/charts/galaxySelector/Points.jsx, src/components/charts/galaxySelector/galaxy-selector.module.scss, src/components/charts/galaxySelector/galaxySelectorUtilities.js, src/components/charts/galaxySelector/index.jsx, src/components/charts/galaxySelector/legend/LegendBox.jsx, src/containers/GalaxiesSelectorContainer.jsx, src/containers/GalaxySelectorContainer.jsx, src/containers/SupernovaSelectorWithLightCurveContainer.jsx, src/data/pages/effects-of-expansion.json, src/data/pages/exploring-lsst-data-2.json
As selections are made in GalaxiesSelector both it and corresponding plot "highlight" active selection;
Any time an existing selection is clicked in either the selector or plot it becomes active in both the selector and the plot and therefore "highlighted";
Includes updates to other components using GalaxySelector to accept null selections;
=> [EPO-2794] GalaxiesSelector selections synchronized with GalacticProperties plot

src/containers/GalaxiesSelectorContainer.jsx, src/state/GlobalStore.js
Previously, when random data option was true GalaxiesSelector fetched random data and then immediately created an answer in order to persist the data across pages.  That was causing a race condition between the fetch and GlobalState updating when visiting the page for the first
with nothing previously saved in localStorage.  This update punts the answer creation to DidUpdate avoiding since the answer creation is not vital until after you click through to a different page.  This avoids the race altogether
=> [B] Fix globalState race condition in randomData

src/components/charts/galaxySelector/blinker/BlinkerImage.jsx, src/components/charts/galaxySelector/blinker/blinker.module.scss, src/components/charts/galaxySelector/index.jsx, src/components/charts/lightCurve/index.jsx, src/containers/GalaxySelectorContainer.jsx, src/data/pages/interpreting-hubble-plot-1.json
When clicking previous/next galaxy buttons below slideout HubblePlot:
- If new activeGalaxy is already selected in GalaxySelector then highlight point in HubblePlot
- If the activeGalaxy is not selected in GalaxySelector then close HubblePlot and update GalaxySelector
=> [EPO-2891] GalaxySelectorHubblePlot advances to next unselected galaxy

src/components/charts/largeScaleStructurePlot/2DChart.jsx, src/components/charts/largeScaleStructurePlot/LargeScaleStructureScatterPlot.jsx, src/components/charts/largeScaleStructurePlot/index.jsx, src/components/page/blocks/WidgetBlock.jsx, src/containers/LargeScaleStructureComboPlotContainer.jsx, src/data/pages/change-over-time-4.json
Structure of the 2d Chart has been massaged and updated to accept the data format currently being consumed by the 3d Chart. Both charts will update according to the slider in the 3d Chart (i.e. the selected data displayed).
Note: may need to break out the slider into the parent container to have more fluid functionality.
=> [EPO-2836] pull in code and create new custom parent component for the Large Scale Structure (side by side)

src/components/charts/shared/navDrawer/index.jsx, src/components/charts/shared/navDrawer/toolbar/index.jsx, src/containers/GalaxySelectorContainer.jsx
Addresses an issue with the NavDrawer update cycle that was causing the full menu toggle "close" method to fire infinitely;
=> [B] GalaxySelector NavDrawer toggle opens/closes full NavDrawer menu

src/components/charts/histogram/index.jsx, src/components/charts/shared/Tooltip.jsx, src/components/site/imageLoader/index.jsx
Previously was using the position of the bar in the histogram to position tooltip but was causing inconsistencies: using mousePos and top of the chart is way more consistent although less elegant
=> [EPO-3025] Histogram Tooltip pos uses mousePos & chartHeight

src/components/charts/galacticProperties/Point.jsx, src/components/charts/galacticProperties/index.jsx, src/components/charts/galaxySelector/index.jsx, src/components/charts/hubblePlot/Point.jsx, src/components/charts/lightCurve/Point.jsx, src/components/charts/sizeDistancePlotter/Point.jsx, src/containers/GalaxiesSelectorContainer.jsx
Removes `raise()` D3 method from Point components: this disruption of the DOM elements' order was in conflict with React's DOM updates in cases where the chart data was dynamic (user generated).  Shouldn't effect charts whose data does not change (or when it changes triggers full graph re-render) but pulled out `raise()` everywhere just to be safe
=> [EPO-3106] GalacticProperties active point matches data

src/components/site/imageLoader/index.jsx
The timeout and it's management in the lifecycle were intermittently
causing errors related to state change on unmounted components.  This
timeout is not really criutical and, arguably, percipitating a worse
experience than if an unloaded image always retained the loading graphic
so we're gonna comment out the timeout stuff for now and assess its
implementation later
=> [B] Removes ImageLoader timeout

src/containers/GalaxiesSelectorContainer.jsx, src/data/pages/exploring-the-deep-1.json, src/data/pages/exploring-the-deep.json, src/lib/utilities.js
In GalaxiesSelectorContainer, the domains for the x and y axes of the accompanying brightness vs distance graph are derived from the extent of whatever data is supplied
=> [EPO-3107] GalaxiesSelector supports data defined domains

src/components/site/header/index.jsx, src/components/visualizations/orbitalViewer/Orbital.jsx, src/components/visualizations/orbitalViewer/OrbitalDetails.jsx, src/components/visualizations/orbitalViewer/Orbitals.jsx, src/components/visualizations/orbitalViewer/index.jsx, src/components/visualizations/orbitalViewer/orbital-viewer.module.scss, src/containers/OrbitalViewerContainer.jsx, src/data/pages/close-to-earth-1.json, src/data/pages/close-to-earth-2.json, src/data/pages/close-to-earth-3.json, src/data/pages/close-to-earth-4.json, src/data/pages/close-to-earth-5.json, src/data/pages/close-to-earth-6.json, src/data/pages/close-to-earth-7.json, src/data/pages/determining-orbits-1.json, src/data/pages/milky-way-introduction.json, src/data/pages/window-stars-introduction.json
Previously the details table was so big it had to go under the fold and below the OrbitViewer.  This update nests the details table within the OrbitViewer and provides a toggle button to reveal/hide the details.  Toggle button is disabled if no object details.
=> [F] OrbitViewer details table fits inside component footprint

src/components/charts/colorMixingTool/color-tool.module.scss, src/components/site/header/header.module.scss, src/components/site/header/header.test.js, src/components/site/header/index.jsx, src/components/site/selectField/styles.module.scss, src/components/site/slider/styles.module.scss, src/layouts/index.jsx
- Add `allInvestigationsJson` query to get all investigations' title.
- Filter titles returned on current `investigation` prop provided.
=> [EPO-3414] Add Investigation title to Header

src/components/site/header/header.test.js, src/components/site/header/index.jsx, src/components/site/tableOfContents/index.jsx, src/containers/EndingContainer.jsx, src/containers/LandingContainer.jsx, src/layouts/index.jsx, src/state/GlobalStore.js
Used the pages' index (+ 1) and stored that in the pages array as 'pageNumber' before storing the pages into global store.
Used that pages array in the Table of contents simply by adding the new pageNumber index in the primaryText.
Pushed a filtered array of pages (only page.id and page.pageNumber) into the Header component. Used the 'lodash/find' to get the page from my new pages array and set that to a pageNumber variable that outputs ": Page {pageNumber}". Imported globalHistory from '@reach/router' and used it's location.pathname prop to catch the page url for the 'last-page' instance as well as the introduction page.
=> [F] Add page numbers to header and table of contents

src/components/qas/index.jsx, src/components/qas/questions/qaCalculator/index.jsx, src/components/qas/questions/qaCompound/index.jsx, src/components/qas/questions/qaExpansionList/QAExpansionPanel.jsx, src/components/qas/questions/qaExpansionList/index.jsx, src/components/qas/questions/qaExpansionList/styles.module.scss, src/components/qas/questions/qaMultiSelect/index.jsx, src/components/qas/questions/qaSelect/index.jsx, src/components/qas/questions/qaTextInput/index.jsx, src/components/qas/styles.module.scss, src/containers/PageContainer.jsx, src/layouts/index.jsx, src/state/GlobalStore.js
When getting total qas on page, set questions numbers by page
Use stored qa number in global store to populate question number
Format and catch all breaking layouts within labels to have number sit
next to first line in label
=> [EPO-3416] Add question numbers to investigations

src/components/visualizations/orbitalViewer/Observation.jsx, src/components/visualizations/orbitalViewer/Observations.jsx, src/components/visualizations/orbitalViewer/Orbital.jsx, src/components/visualizations/orbitalViewer/Orbitals.jsx, src/components/visualizations/orbitalViewer/PotentialOrbits.jsx, src/components/visualizations/orbitalViewer/index.jsx, src/components/visualizations/orbitalViewer/orbital-viewer.module.scss, src/components/visualizations/orbitalViewer/orbitalUtilities.js, src/containers/OrbitalViewerContainer.jsx, src/containers/WithQAing.jsx, src/data/pages/determining-orbits-4.json, src/fragments/widget.js, src/fragments/widgetOptions.js
Observation points are clickable and produce answers;
Style changes on hover and click, and in presence of correct selection;
Observations points positions are defined in relation to the mean curve when averaging potential orbits data (i.e. can only be used in conjunction with the potential orbits);
=> [EPO-3122] OrbitViewer supports Observation points

yarn.lock
version bump to suppress warning
=> Update caniuse browserlist dependency

src/components/charts/galaxySelector/Point.jsx, src/components/charts/galaxySelector/Points.jsx, src/containers/AstroToolContainer.jsx, src/containers/GalaxiesFilterSelectorContainer.jsx, src/containers/GalaxiesSelectorContainer.jsx, src/containers/GalaxyScramblerContainer.jsx, src/containers/GalaxySelectorContainer.jsx, src/containers/HubblePlotContainer.jsx, src/containers/OrbitalViewerContainer.jsx, src/containers/PrismWidgetContainer.jsx, src/containers/SupernovaSelectorWithLightCurveContainer.jsx, src/containers/TimeDomainViewerContainer.jsx
updateAnswer is an alias for the answer handler func in GlobalStore;
This update ensures all calls to this func in widgets and various question
types include a string ref to indicate type (options are null, 'focus', 'blur', 'change');
Crucially, using non-null values where appropriate in order to trigger update to activeQuestion in global store
=> [B] All calls to updateAnswer include appropriate 'type' param

src/components/visualizations/orbitalViewer/OrbitalDetails.jsx
JIRA: https://jira.lsstcorp.org/browse/EPO-4333
Per Content Admin request, remove absolute magnitude and Earth MOID. Update 'semi-major axis' to 'orbit size' as well.
This change is effected in only one file ../components/visualizations/orbitalViewer/OrbitalDetails.jsx. This change will affect any instance of this widget.
- 10 = "I think it works, I can explain how, but only over screen share"
The level of review requested is a 4. Although I know the change is effective, I want to be certain this is the proper and anticipated approach.
This change has been tested by viewing this …
=> [EPO-4333] Remove fields and update name

src/components/charts/galaxiesPosition3D/index.jsx
JIRA: https://jira.lsstcorp.org/browse/EPO-4341
Did some digging within the provided examples here at this website, and found this example where I was able to change the `show: true` parameter to `false` and _viola!_
Applied what I learned and removed the grid, axes, and coordinate numbers with this simple little param designated by:
```
grid3D: {
show: false, <--- this little guy here
bottom: ...
...
}
```
Next step in the 3D Widget's evolution!!!!
This change can be found in the ../components/galaxiesPosition3D/index.jsx file at /expanding-universe/testing-law/ of the Expanding investigation.
- 5 = "Please make sure there are no obvious errors and that you believe it does what …
=> [EPO-4341] Remove the grid, axes, and coordinate numbers in 3D Widget

src/assets/stylesheets/_variables.scss, src/components/charts/hubblePlot/AxisGrid.jsx, src/components/charts/hubblePlot/XAxis.jsx, src/components/charts/hubblePlot/YAxis.jsx, src/components/charts/hubblePlot/hubble-plot.module.scss, src/components/charts/hubblePlot/index.jsx
JIRA: https://jira.lsstcorp.org/browse/EPO-4340
Add grind line to hubble plot by creating a new component that builds the svg based off the tick lines.. Component allows for a specified number of grid lines if needed.
Changes/Additions can be found in `/components/charts/hubblePlot/index.jsx`, `/components/charts/hubblePlot/AxisGrid.jsx`, `/components/charts/hubblePlot/hubble-plot.moduel.scss` and `/assets/stylesheets/_variables.scss`.
- 10 = "I think it works, I can explain how, but only over screen share"
**Requesting review level 5**
If any of the following are true, please …
=> [EPO-4340] Add grid lines to hubble plot

src/components/charts/galaxiesPosition3D/index.jsx
JIRA: https://jira.lsstcorp.org/browse/EPO-4342
Add connecting lines from the Milky Way galaxy to each individual galaxy. 
In order to create a line for each connection individually, I had to build an array of objects and spread them into the series array.
Updates can be found in the `/components/charts/galaxiesPosition3D/index.jsx`
- 10 = "I think it works, I can explain how, but only over screen share"
**Requesting a level 5 review**
Visually ? :) 
=> [EPO-4342] Add connecting lines from MW to each galaxy

src/components/site/imageLoader/index.jsx
JIRA: [EPO-4419](https://jira.lsstcorp.org/browse/EPO-4419)
Re-implements timeout on lazy-loaded images.  The timeout should ensure that the image becomes visible after 4 secs, even if the `onload` has not fired, even if the image has not finished loading.
This is a change we'll have to keep an eye on on staging due to challenges testing.
1 = "I barely need review on this"
Tested locally by throttling network in chrome devTools, and on staging by checking when `console.log`s fired in the timeout callback vs the `onload` handler.  Console.logs have since been removed, but can still test on staging by observing when or if images in the investigation load in 4 secs or less.
=> [EPO-4419] Fix lazyloading

src/components/widgets/widgets-utilities.js, src/containers/GalaxySupernovaSelectorContainer.jsx, src/containers/WithQAing.jsx, src/data/pages/interpreting-hubble-plot-1_2.json, src/data/pages/interpreting-hubble-plot-1_3.json, src/data/pages/interpreting-hubble-plot-1_4.json, src/data/pages/interpreting-hubble-plot-2.json, src/data/pages/interpreting-hubble-plot-3.json, src/fragments/widgetOptions.js
JIRA: https://jira.lsstcorp.org/browse/EPO-4405
This change adds tables to the new pages created from [EPO-4404](https://jira.lsstcorp.org/browse/EPO-4404) that stores and persists the `distance` and `velocity` values from the selection of the new GalaxySupernova widget on each page.
Take a look at how the data is being returned from within the widget as well as how the `WithQAing.jsx` component is returning the content for the question component.
Requesting a review level of **7**
This update can be tested by selecting a galaxy and supernova on `interpreting-a-hubble-plot-1/` then clearing out the selection with the "clear" option on the question. After the selection is made, moving on to the new page to see your selection persist in the table. Make sure that each page in the series …
=> [EPO-4405] Add tables to new GalaxySupernova pages

src/assets/stylesheets/_variables.scss, src/components/charts/colorMixingTool/color-tool.module.scss, src/components/visualizations/orbitalViewer/orbital-viewer.module.scss
JIRA: [EPO-4424](https://jira.lsstcorp.org/browse/EPO-4424)
Updates the OrbitViewer and ColoringTool containers to be responsive down vertical height of 768px and horizontal width of 1024px, and any/range.combination therein.
Evaluated all widgets in Expanding Universe, Coloring the Universe, and Surveying the Solar System.  Found all were laying out acceptably but for the OrbitViewer and the ColoringTool (and its no controls variant)
Include an indication of how detailed a review you want on a 1-10 scale: 5 = "Please make sure there are no obvious errors and that you believe it does what it says it does"
Squish that browser window all over the darned place.
=> [EPO-4339] Right col widgets fit on screens as small as 1024 x 768

src/components/charts/asteroidClass/index.jsx, src/components/charts/galacticProperties/index.jsx, src/components/charts/hubblePlot/index.jsx, src/components/charts/sizeDistance/index.jsx
JIRA: [EPO-4400](https://jira.lsstcorp.org/browse/EPO-4400)
HubblePlot is zoomable if it is a HubblePlot where the user is placing points.  Non-interactive HubblePlots and Trendline placement HubblePlots are not zoomable.
Uses same D3 zoom strategy as implemented in other D3 SVGs like the light curve templates.
Include an indication of how detailed a review you want on a 1-10 scale: 5 = "Please make sure there are no obvious errors and that you believe it does what it says it does"
[Best example of this kind of HubblePlot currently](https://604a8a09a7e41a00075439a7--investigations.netlify.app/expanding-universe/interpreting-a-hubble-plot-2/) (I guess will change as @georgegomez144 finishes creating a standalone "HubblePlotter" component).
If any of the following are true, please check …
=> [EPO-4400] HubblePlot is zoomable

src/components/charts/colorMixingTool/index.jsx, src/components/site/tableOfContents/index.jsx, src/components/site/tableOfContents/table-of-contents.module.scss
JIRA: https://jira.lsstcorp.org/browse/EPO-4402
Disable TOC links when the earlier questions have not been answered to keep from "jumping around" in the investigation.
Create a new css class that disables `pointer-events`. This works in tandem with the `disabled` param on the `links` object created in the TOC. I'm also mutated (slightly) the `checkQAProgress` function in the `tableOfContents/index.jsx` that now takes a specific `state` (e.g. 1 or 0) to determine the state of the page in question. I then use this to determine in disabled state of each link per its page. Works nicely with the progress states.
Include an indication of how detailed a review you want on a 1-10 scale. **5 = "Please make sure there are no obvious errors and that you believe it does what it says it does"** …
=> [EPO-4402] Disable TOC links if earliest questions not answered

package.json, src/components/qas/styles.module.scss, src/containers/QAReviewContainer.jsx, src/fragments/pageMeta.js
JIRA: https://jira.lsstcorp.org/browse/EPO-4399
This commit updates the GraphQL query to use the PageContainer's query in order to set up and pull in all elements of the investigation. This also includes the `ObservationsTable` component in order to render the "now available" tables in the QA Review page.
Changes can be found on the `qa-review` page. Look for the tables loaded at the bottom of the QA Review page.
Include an indication of how detailed a review you want on a 1-10 scale. **5 = "Please make sure there are no obvious errors and that you believe it does what it says it does"**
Testing this change can be seen by "filling in" the tables through the investigation and checking to see the answer is correctly populated in the QA Review page.
If any of the following are true, please …
=> [EPO-4399] Add tables to QA Review page

src/components/charts/prismWidget/prism-widget.module.scss, src/components/qas/styles.module.scss, src/containers/QAReviewContainer.jsx
JIRA: https://jira.lsstcorp.org/browse/EPO-4397
This change adds the widgets to the QA Review page. Used the same method of the tables to load these widgets. Created a container class to make sure the widget fits in the bounds of the page.
Well, the QA Review page is the place to be when reviewing this PR.
There is a style change to the PrismTool that was breaking on the QA Review page, and well, this change makes the layout in the investigation a little cleaner.
**5 = "Please make sure there are no obvious errors and that you believe it does what it says it does"**
n/a
=> [EPO-4397] Add widgets to the QA Review page

src/components/qas/styles.module.scss, src/containers/QAReviewContainer.jsx, src/data/pages/asteroid-impact-3.json, src/data/pages/determining-orbits-1.json, src/data/pages/determining-orbits-1a.json, src/data/pages/determining-orbits-5-1.json, src/data/pages/haz-summary-4.json, src/data/pages/haz-summary-5.json, src/data/pages/interpreting-hubble-plot-1_2.json, src/data/pages/interpreting-hubble-plot-1_3.json, src/data/pages/interpreting-hubble-plot-1_4.json, src/data/pages/interpreting-hubble-plot-2.json, src/data/pages/nebula-theory.json
JIRA: https://jira.lsstcorp.org/browse/EPO-4350
This change ensures that questions/pages load in order as shown in the investigation on the QA Review page. This change also adds the question numbers. I used a similar method found in the `PageContainer.jsx` file.
There were a few `.json` pages that were updated (the `order` field) to make sure that the pages/questions are loaded correctly in order.
Include an indication of how detailed a review you want on a 1-10 scale: **5 = "Please make sure there are no obvious errors and that you believe it does what it says it does"**
n/a
=> [EPO-4350] Order and add number to pages in QA Review

src/assets/stylesheets/components/charts/_tooltip.scss, src/components/charts/hubblePlot/Points.jsx, src/components/charts/hubblePlot/index.jsx
JIRA: [EPO-4468](https://jira.lsstcorp.org/browse/4468)
- If active galaxy has no point placed user should see "ghost point" and be able to place point on 
- If active galaxy has a point already user should be able to adjust its placement by dragging and dropping
- If user clicks or drags a non-active galaxy point that point and its corresponding galaxy should become active
- This new interactivity should be scoped to the HubblePlotter only (not the normal HubblePlot or the HubblePlotWIthTrendline or the combo with the 3D stufff)
To work around the drag event colliding with the normal click event I had to get creative in terms of what a drag-start and drag-end events trigger, especially in the absence of any drag fired in between.  Feels...a bit frail, but held up in testing.
This is a 7. …
=> [EPO-4468]  HubblePlotter points are draggable

src/assets/stylesheets/STACSS/_typography.scss, src/components/pageNav/index.jsx, src/components/pageNav/page-nav.module.scss, src/components/site/answerRequiredAlert/answer-required.module.scss, src/components/site/answerRequiredAlert/index.jsx, src/components/site/icons/Stop.jsx
JIRA: https://jira.lsstcorp.org/browse/EPO-4466
This change adds the Answers Required svg that José created. This alert will trigger on click of the next page button when there are answers that are not filled out.
AnswerRequired Alert component is built similarly to the checkpoint component. "Disabled" button that triggers the alert renders instead of next button on disabled.
Include an indication of how detailed a review you want on a 1-10 scale. - **5 = "Please make sure there are no obvious errors and that you believe it does what it says it does"**
clicking between pages and such
=> [EPO-4466] Add AnswerRequiredAlert component

src/components/charts/colorMixingTool/index.jsx, src/components/charts/prismWidget/index.jsx, src/containers/AstroToolContainer.jsx, src/containers/GalaxiesFilterSelectorContainer.jsx, src/containers/GalaxySupernovaSelectorContainer.jsx, src/containers/PrismWidgetContainer.jsx, src/containers/QAReviewContainer.jsx
JIRA: https://jira.lsstcorp.org/browse/EPO-4398
Add some additional customizations to certain widgets inorder to "disable" their functionality on the QA Review page. I utilized the `qaReview: false` param and passed that into the widgets on the QA Review page and from there utilized that as a way to `disable` any interactable widget features still functional on the QA Review page. I also utilized the predefined options (`preSelected: true`, `autoplay: false`) to render the widgets inactive.
n/a
Include an indication of how detailed a review you want on a 1-10 scale.: **5 = "Please make sure there are no obvious errors and that you believe it does what it says it does"**
n/a
=> [EPO-4398] Disable all widgets on the QA Review Page

src/assets/stylesheets/components/charts/_tooltip.scss, src/components/charts/histogram/index.jsx, src/components/charts/orbitalProperties/index.jsx, src/components/charts/shared/Tooltip.jsx, src/data/pages/characterizing-comet.json, src/data/pages/characterizing-mba.json, src/data/pages/characterizing-neo.json, src/lib/utilities.js
JIRA: https://jira.lsstcorp.org/browse/EPO-4473
This change updates the tooltips in the histograms to now show "<number> out of <total_number>" when using the `countOfTotal` in `tooltipAccessors`. This is change required me to add another custom accessor type in the Tooltip component.
This change can be found in the Histogram component as well as in the Tooltip component. Small note, I added an `id` to the CircularProgress component on the OrbitalProperties component because it was firing and error within console.
Include an indication of how detailed a review you want on a 1-10 scale.: **5 = "Please make sure there are no obvious errors and that you believe it does what it says it does"**
By hovering the mouse of the bins in the histograms to show the tooltip.
If any of the following are …
=> [EPO-4473] Update histogram tooltip to allow "out of" totals

src/assets/stylesheets/_variables.scss, src/components/charts/prismWidget/index.jsx, src/components/charts/prismWidget/prism-widget.module.scss
JIRA: https://jira.lsstcorp.org/browse/EPO-4552
This change "migrates" the prism tool structure from HTML to SVG for cleaner animations and scaling between browsers. The update also removes all unused styles and code.
Changes can be found in both the `/prismWidget/index.js` as well as its `prism-widget.module.scss`.
Include an indication of how detailed a review you want on a 1-10 scale: - 5 = "Please make sure there are no obvious errors and that you believe it does what it says it does"
n/a
=> [EPO-4552] Replace prism html with svg

gatsby-browser.js, src/components/charts/colorMixingTool/FilterImage.jsx, src/components/charts/colorMixingTool/color-tool.module.scss, src/components/charts/colorMixingTool/index.jsx, src/components/qas/styles.module.scss, src/components/site/slider/index.jsx
JIRA: https://jira.lsstcorp.org/browse/EPO-4651
No longer will it use the 'background-image' property (since that does not render in printer view). Now comes the time for the "CANVAS" element, which does render as asked.
Still a bit buggy since, the filtered images won't load "right-off-the-bat" when previously answered.
n/a
=> [EPO-4651] Update Color Filter Tool to use the canvas element

src/components/pageNav/index.jsx, src/components/site/answersCompletedAlert/answers-completed.module.scss, src/components/site/answersCompletedAlert/index.jsx, src/components/site/icons/Checkmark.jsx
JIRA: https://jira.lsstcorp.org/browse/EPO-4648
This change adds a new all questions answered alert that notifies the student that all questions on the page have been answered and that they may continue onto the next page. This alert includes a close button and a 'go to next page' button.
Had to add a catch for this notification in the PageNav/index.jsx so that the modal could close. Also, I was able to add the 'go to next page' button into the modal by passing in the next page info into the new component.
Answer all questions on the page and watch the magic!
=> [EPO-4648] Add "All Questions Answered" notification

src/containers/QAReviewContainer.jsx
JIRA: https://jira.lsstcorp.org/browse/EPO-4660
Date stamp added under the name and is only visible on the print page.
n/a
Include an indication of how detailed a review you want on a 1-10 scale. - 1 = "I barely need review on this"
Print the QA Review page and check to see the date is visible.
=> [EPO-4660] Add date stamp on QA Review page

src/assets/stylesheets/STACSS/_appearance.scss, src/assets/stylesheets/_variables.scss, src/components/charts/galacticProperties/galactic-properties.module.scss, src/components/charts/galacticProperties/index.jsx, src/containers/GalacticPropertiesComboContainer.jsx
JIRA: https://jira.lsstcorp.org/browse/EPO-4712
This change applies the same dataset color logic as the Galaxy/Hubble Plot selector widget to the galactic properties widget in order to automate the dataset color relationship.
This change primary resides in the `galactic-properties.module.scss` in more 'generic' classes (`&.inactive-#{$i}` and `&.active-#{$i}`). These two classes' styling trickles down to style their svgs, background-colors, and text according to the defined `$chartColors` found in the `_variables.scss`.
n/a
=> [EPO-4712] Add dataset color matching in scatter plots

src/components/charts/shared/StellarValue.jsx, src/components/qas/questions/qaCalculator/equations/FindKineticEnergy.jsx, src/lib/utilities.js
JIRA: https://jira.lsstcorp.org/browse/EPO-4715
This change adds the `scientificNotation()` into the mix. This function will convert the value given into scientific notation through a specified sigFig. If no sigFig is specified, then it defualts to 3. If the number is greater than 1 or less than -1 and has 9 or fewer digits or if the number is between 1 and -1 and has 3 or fewer digits after the decimal the function will return that number rounded to sig figs.
Added the ability for the table cell to render the HTML if present.
n/a
=> [EPO-4715] Add new Scientific Notation function

src/components/site/mathJax/mathJax.module.scss
JIRA: https://jira.lsstcorp.org/browse/EPO-4804
After trying a few solutions I've ended up on a suggestion by Blake. As of now, the svg within the MathJax component is only allowed to stretch to its container's width. In keeping with this logic (as we do not want the equation to every "overflow" its container), I'm implementing the suggestion from Blake to adjust the font size of the svg itself in the css. If the font size is 18px it should address the font size being larger than the standard copy on the page (which, I believe is 16px). 18px is neither too small nor too large in comparison copy on page and will certainly suit the needs of this ticket. Also having the svg not "overflow" its bounds (parent container) the font will scale as needed when additional space is required in the …
=> [EPO-4804] Change MathJax svg font to 18px and keep max-width

src/components/charts/galaxySelector/index.jsx, src/containers/SupernovaSelectorWithLightCurveContainer.jsx, src/data/pages/blinking-supernovae.json, src/data/pages/searching-for-supernovae-1.json, src/data/pages/searching-for-supernovae-2.json, src/data/pages/searching-for-supernovae-3.json, src/fragments/widgetOptions.js
- Ensures autoplay functionality still works
- Sets new loop prop default to `true`
- When loop is `false` animation will stop ready to start again
from first frame
JIRA: https://jira.lsstcorp.org/browse/EPO-4839
This change adds the `loopAnimation` option in the json data and its defaultProp is set to `true`. If `loopAnimation` is set to `false`, the animation will play to the end and stop. When the play button is triggered again the animation will begin from the first frame.
n/a
n/a
=> [EPO-4839] Add loop option for blink animation

src/assets/stylesheets/_variables.scss, src/components/charts/galaxySelector/index.jsx, src/components/charts/shared/elapsedTime/elapsedTime.module.scss, src/components/charts/shared/elapsedTime/index.jsx, src/data/pages/searching-for-supernovae-1.json
JIRA: https://jira.lsstcorp.org/browse/EPO-4840
This change adds the Elapsed Time indicator to the Galaxy selector widget that displays the elapsed days and hours of each alert. The indicator is its own separate component that takes two props, days and hours. 
n/a
n/a
=> [EPO-4840] Add the Elapsed Time indicator

src/components/charts/galacticProperties/Trendline.jsx, src/components/charts/galacticProperties/index.jsx
JIRA: https://jira.lsstcorp.org/browse/EPO-4916
This change adds the Redness trendline to the Flux vs. Distance plot. This trendline was pulled from the Hubble Plot and stripped to create this redness trendline.
Adds two additional trendline parameters to the GalacticProperties widget that controls the visibility and text of the trendline.
**5** "Please make sure there are no obvious errors and that you believe it does what it says it does"
How did you test this change?  Can the reviewers test this change for themselves?
If you wrote new tests in the change it's fine to just put "New tests in PR". If you haven't added any tests but you think your change is covered by existing tests you can say "Existing tests". And …
=> [EPO-4916] Add "Redness" trendline to Flux vs. Dist plot

src/data/pages/characterizing-comet.json, src/data/pages/characterizing-mba.json, src/data/pages/characterizing-neo.json, src/data/pages/characterizing-tno.json
For JIRA: "EPO-5424 #IN-REVIEW #comment Reorder orbital characteristics questions"
JIRA: https://jira.lsstcorp.org/browse/EPO-5424
Re-orders the orbital characteristics pages of Surveying the Solar System to go in order of Semi-major axis, eccentricity, and inclination.
Observe that the semi-major axis questions ("size of the orbit") questions for each of the 4 orbital characteristics pages (NEO, MBA, TNO, Comets) is re-ordered to be ahead of the eccentricity and inclination questions.
4
Tested by using the Surveying the Solar System investigation up through the Orbital Characteristics pages and verifying the order of questions.
=> [C] Reorder Orbital Characteristics questions

src/components/page/SingleCol.jsx, src/components/page/TwoCol.jsx, src/components/page/blocks/ContentBlock.jsx, src/components/page/blocks/QuestionBlock.jsx, src/components/page/blocks/index.jsx, src/containers/PageContainer.jsx
JIRA: https://jira.lsstcorp.org/browse/<ID>
Previously the questions in investigations were rendered outside of the layout flow that the other block components exist in. The `QAs` component has been normalized into a `QuestionBlock` component that accepts a layout position the same as other block components. A default layout for QuestionBlock has also been created at the `PageContainer` level to closely approximate it's previous position after the `middle left` content. 
After looking through several investigations the layouts appear to match their previous position and no major layout change has occurred.
Observe that the questions appear in their expected location and function identically to how they did prior to this change. No work was done on the blocks themselves apart from creating …
=> [C] EPO-5643 - Refactor QAs into QuestionBlock

src/data/pages/history-solar-system.json
JIRA: https://jira.lsstcorp.org/browse/EPO-5704
Fix the Oort Cloud glossary link to navigate to the definition page instead of an anchor link in the main glossary
Verify that the link goes to the Oort Cloud definition page
=> [C] Fix Oort Cloud link

src/components/pageNav/index.jsx
For JIRA: "EPO-5820 #IN-REVIEW #comment Remove answers popup"
JIRA: https://jira.lsstcorp.org/browse/EPO-5820
The pop-up notification that displayed on a 15s delay after answering all questions on the page has been removed.
The pop-up and the enabling code that displays that "You have answered all the questions on the page" notification has been removed. Some of the code is still left in place, particularly to hide the "Please answer all questions before continuing to the next page." pop-up when all questions have been answered.
- 3
Clear local storage of any previously answered questions. Complete a set of questions in a page and wait 15s, no pop-up should display. On another page, try to click forward before …
=> [C] Remove answers popup

src/assets/stylesheets/_variables.scss, src/assets/stylesheets/components/site/progress/_header-progress.scss, src/assets/stylesheets/components/site/progress/_index.scss, src/assets/stylesheets/components/site/progress/_progress-linear.scss, src/components/site/header/HeaderProgress.jsx, src/components/site/header/header.module.scss, src/components/site/header/index.jsx, src/components/site/icons/Checkpoint.jsx, src/components/site/icons/CustomIcon.jsx, src/components/site/icons/Finish.jsx, src/components/site/linearProgress/LinearProgressMarker.jsx, src/components/site/linearProgress/index.jsx, src/components/site/progress/index.jsx, src/components/site/progress/progress.module.scss, src/layouts/index.jsx, src/state/GlobalStore.js
For JIRA: "EPO-5829 #IN-REVIEW #comment Redesign progress bar"
JIRA: https://jira.lsstcorp.org/browse/EPO-5829
Redesign the progress bar in investigations for better visibility and displaying checkpoints
This change creates a new component specifically for the header progress bar that adds checkpoints along with redesigning the baseline styling for all progress bars and adding a marker onto them that when hovered will display the progress percentage.
- 4
Load an investigation and observe that checkpoints are displayed, progress through the investigation and observe the progress marker moving across the bar and the checkpoints turning from gray to green as they are reached. Hover the progress marker and observe the …
=> [F] Redesign investigations progress bar

.stylelintrc, src/assets/stylesheets/_variables.scss, src/assets/stylesheets/components/site/_educator-mode-toggle.scss, src/assets/stylesheets/components/site/_index.scss, src/assets/stylesheets/lib/_md-globals.scss, src/components/pageNav/index.jsx, src/components/site/educatorModeToggle/index.jsx, src/components/site/tableOfContents/index.jsx, src/containers/LandingContainer.jsx, src/layouts/index.jsx, src/state/GlobalStore.js
JIRA: https://jira.lsstcorp.org/browse/EPO-5899
Add educator mode to investigations that can be enabled by users with a password. After enabled users should be able to:
- Navigate through investigations without completing questions
- Pagination buttons are never disabled
- Table of Contents links are never disabled
- “Answer all questions” pop up is disabled
- Toggle to leave/enter educator mode on investigation landing page and in sidebar
Look for consistency in navigation with educator mode enabled/disabled and that changing the state does not leave impact on the other state i.e. that enabling educator mode then returning to student mode does not inappropriately enable links or move progression forward.
- 5 = …
=> [F] Implement educator mode toggle

src/assets/stylesheets/components/site/tables/_cell-inputs.scss, src/components/qas/questions/qaFillableTable/FillableTableRangeInput.jsx, src/components/qas/questions/qaFillableTable/FillableTableTextInput.jsx
JIRA: https://jira.lsstcorp.org/browse/EPO-5948
Fix the display of range inputs in the fillable table cells when they overflow and fix a remaining undefined exception in the QA review
- 3
Test long inputs in the range cell both while in input mode and in static display. Clear all answers and go to the review page.
=> [C] Fix range input overflow and QA review

gatsby-node.js, src/containers/QAReviewContainer.jsx
For git: "Resolves EPO-6062"
For JIRA: "EPO-6062 #IN-REVIEW #comment Make sectionId primary sort"
JIRA: https://jira.lsstcorp.org/browse/EPO-6062
Remove the secondary sorting in QAReviewContainer and use graphQL to sort by sectionId then order, add sectionId sorting to the gatby node build
Check that review questions display in correct order.
- 2
Can test by going to the QAReview page and verifying question order
=> [C] Change QaReview sorting to sectionId primary

gatsby-config.js, src/components/pageNav/index.jsx, src/components/site/tableOfContents/index.jsx, src/containers/EndingContainer.jsx, src/containers/LandingContainer.jsx, src/containers/PageContainer.jsx, src/containers/QAReviewContainer.jsx, src/data/locales/es/interface.json, src/pages/StyleGuide.jsx
For git: "Resolves EPO-6066"
For JIRA: "EPO-6066 #IN-REVIEW #comment set up URL routing for i18n"
JIRA: https://jira.lsstcorp.org/browse/EPO-6066
Set up i18next to add URL path routing for locales. Redirect internal links to the appropriate URL locale. Set up fallback language for missing translations.
This change will allow switching between English and Spanish using the URL path. Only one Spanish translation is currently in place (table of contents -> Tabla de contenido) and the remaining translation keys should display their English fallback.
There are a couple ways to test this, some thought about the order of …
=> [C] set up URL routing for i18n

src/containers/OrbitalViewerContainer.jsx, src/data/pages/classifying-objects-1.json, src/data/pages/classifying-objects-2.json, src/data/pages/classifying-objects.json
JIRA: https://jira.lsstcorp.org/browse/EPO-6065
Adds the capability to pick a random source from a dataset in the orbit viewer and preserve it using the global store
Change is limited to the `OrbitViewerContainer` component and then the 3 "classifying objects" pages
- 3
Test by visiting classifying-objects, classifying-objects-1, and classifying-objects-2 and checking that each displays an individual orbit. Revisit each page and confirm that the same orbit is displayed.
Clear the local storage and reload the application, verify that each page now displays a different orbit (it's possible one could display the same orbit again but the odds are very very low, if each one shows the same orbit you are either in danger of …
=> [C] Add orbital randomization

src/assets/stylesheets/STACSS/_appearance.scss, src/assets/stylesheets/_variables.scss, src/assets/stylesheets/components/site/_index.scss, src/assets/stylesheets/components/site/_language-toggle.scss, src/assets/stylesheets/components/site/_switch.scss, src/components/site/header/index.jsx, src/components/site/switch/index.jsx, src/containers/LanguageToggleContainer.jsx, src/data/locales/en/interface.json, src/data/locales/es/interface.json
For git: "Resolves EPO-6124"
For JIRA: "EPO-6124 #IN-REVIEW #comment add english-spanish toggle"
JIRA: https://jira.lsstcorp.org/browse/EPO-6124
Add a toggle button to switch between English language and Spanish
Review the changes using the deployment in this PR
- 3
Test in the deployment attached to this PR. Verify that toggling the button switches between English and Spanish. When toggling to Spanish, URL's should be prepended with "es" and there is a translation for "Table of Contents" that will change based on language. 
**Feedback requested** the locale switch reloads the page, there is a very brief flash of the scrollbar displaying on the page which makes it appear to flicker. It may take some effort to trace …
=> [F] english-spanish toggle button

src/components/site/debug/index.jsx, src/containers/LandingContainer.jsx, src/data/locales/en/interface.json
For git: "Resolves EPO-6248"
For JIRA: "EPO-6248 #IN-REVIEW #comment add debug output to investigations"
JIRA: https://jira.lsstcorp.org/browse/EPO-6248
Add a debugging tool that downloads an output containing the current application state with additional information like browser agent, online status, timestamp, and current URL
Test by loading the landing page of investigations and clicking the new "debug" link at the bottom of the page. Verify that a txt file downloads and contains information.
- [x This change is isolated to a specific page or Component (i.e. it's a one-off)
=> [F] Add debug output to investigations

src/components/site/debug/index.jsx, src/data/locales/en/interface.json, src/layouts/index.jsx, src/state/GlobalStore.js
For git: "Resolves EPO-6247"
For JIRA: "EPO-6247 #IN-REVIEW #comment reset global state when clearing"
JIRA: https://jira.lsstcorp.org/browse/EPO-6247
Resolves a bug where when resetting the global state, the callback updates the local storage with the global state pre-reset. This would result in not being able to clean out old code stored locally. Instead reactn's built-in reset tool is used and the callbacks and reducers are reset at the same time.
Where should the reviewer look for the change?  Do they review the change on the frontend?  How extensive is the change?  Does it affect Components used in a variety of contexts?  Anything you'd like reviewers to pay particular attention to or questions you have about the change.
Include an indication of how detailed a review you want on a …
=> [C] reset global state when clearing answers

src/components/qas/questions/qaMultiSelect/index.jsx, src/components/qas/questions/qaSelect/index.jsx
JIRA: https://jira.lsstcorp.org/browse/EPO-7066
Instead of translating labels and values for selections, only translate the labels so that the value key can be preserved and answers be able to change between locales
Fill out answers up to a single or multi-select answer, make a selection then change the locale and verify the selection is preserved when locales change. Verify the selection is preserved on the QAReview page when locale is changed
- 3
=> [C] only translate select labels

src/components/charts/hubblePlot/Nudge.jsx, src/components/charts/hubblePlot/Points.jsx, src/components/charts/hubblePlot/hubble-plot.module.scss, src/components/charts/hubblePlot/index.jsx, src/components/site/sliderVertical/index.jsx, src/components/site/sliderVertical/styles.module.scss, src/components/visualizations/orbitalViewer/PlaybackSpeed.jsx, src/components/visualizations/orbitalViewer/orbital-viewer.module.scss
JIRA: https://jira.lsstcorp.org/browse/EPO-7067
Moves the slider component in the orbit viewer into its own component and implements it to control zoom in the Hubble plotter
This change is two minor changes, porting a component and then implementing it. An additional check should be made on top of checking out the Hubble plotter to verify that the orbit viewer slider is still functioning.
- 5
Start Expanding Universe and go forward to the `/interpreting-a-hubble-plot-2` page, test the zoom both using the slider and mouse and combinations of the two. Start Surveying the Solar System and go to `/identifying-groups-1` and verify the slider on this page is still functioning as well.
If any of the following are true, …
=> [F] Add Hubble plotter slider

src/containers/GalaxySupernovaSelectorContainer.jsx, src/data/pages/interpreting-hubble-plot-1.json, src/data/pages/interpreting-hubble-plot-1_2.json, src/data/pages/interpreting-hubble-plot-1_3.json, src/data/pages/interpreting-hubble-plot-1_4.json
For JIRA: "EPO-7152 #IN-REVIEW #comment randomize galaxy/supernova selector"
JIRA: https://jira.lsstcorp.org/browse/EPO-7152
Randomize the galaxy/supernova selector order
Check the deployment, change is localized to expanding universe with a few changes to page data and some new code in the galaxy/supernova selector component container
- 4
Clear answers for Expanding Universe, go forward to `interpreting-a-hubble-plot-1/` and verify a galaxy loads, then check the following 3 pages. Revisit each page to verify that the same galaxy loads each time. Clear answers and repeat the process, this time verifying that there has been some change in the order of the galaxy/supernova pairrings displayed.
If any of the following …
=> [C] randomize galaxy/supernova selector

src/containers/LandingContainer.jsx, src/state/GlobalStore.js
JIRA: https://jira.lsstcorp.org/browse/EPO-7358
Add a "Reset" button in addition to the existing "Clear Answers" button that displays when users have a non-fresh local storage, but have not answered any questions
-3 
Testing can be done by making some change to the investigation, but not answering questions, and returning to the landing page to determine if a "Reset" button is available. Press "Reset" then observe it disappearing and the application returning to a fresh state. Refreshing the page after this should not make it return, neither should changing the page and returning.
Reset should not appear if questions have been answered. 
=> [C] additional reset options

src/components/seo.jsx
For JIRA: "EPO-7676 #IN-REVIEW #comment get lang attribute from i18next"
JIRA: https://jira.lsstcorp.org/browse/EPO-7676
Set the html `lang` attribute using the currently set language from i18next
Verify on frontend that the `lang` attribute is set on the `html` element and updates when the language is changed
=> [C] get lang attribute from i18next
